task_cls: tasks.vocoder.hifigan.HifiGanTask
resblock: "1"
adam_b1: 0.8
adam_b2: 0.99
upsample_initial_channel: 512
resblock_kernel_sizes: [ 3,7,11 ]
resblock_dilation_sizes: [ [ 1,3,5 ], [ 1,3,5 ], [ 1,3,5 ] ]

use_pitch_embed: false
use_fm_loss: false
use_ms_stft: false
use_cond_disc: false

lambda_mel: 5.0
lambda_mel_adv: 1.0
lambda_cdisc: 4.0
lambda_adv: 1.0

lr: 0.0002            # Generator's learning rate.
generator_scheduler_params:
  step_size: 600
  gamma: 0.999
discriminator_scheduler_params:
  step_size: 600
  gamma: 0.999
max_updates: 3000000

low_resrc_langs:
  - name: English
    commonvoice_name: en
    phonemizer: en-us
    lang_id: 1
use_spk_embed: false
binarization_args:
  with_wav: true
upsample_rates: [ 5,4,4,4 ]
upsample_kernel_sizes: [ 10,8,8,8 ]
max_sentences: 48
val_max_batches: 100
audio_num_mel_bins: 80
profile_infer: false
vocoder_ckpt: checkpoints
